name: JUNIT-1

on:
  workflow_dispatch:  

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code (again, for this job)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven  
      - name: Run JUnit Tests
        working-directory: Spring-Boot-main 
        run: mvn test  
      - name: Generate JUnit Report (optional)
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: 'Spring-Boot-main/target/surefire-reports' # Adjusted path to include the directory
      - name: Display Test Results Summary
        run: |
          echo "Test Results Summary:"
          cat Spring-Boot-main/target/surefire-reports/*.txt  # Assuming test summary is stored in a text file
