name: UNIT_TEST
 
on:

  workflow_dispatch:  
 
jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3  # Checkout the repository code
 
  run-tests:

    name: Run Tests

    runs-on: ubuntu-latest

    needs: build  

    permissions:

      contents: read 

      packages: write  

    steps:

      - uses: actions/checkout@v3  
      - name: Set up JDK 17

        uses: actions/setup-java@v3

        with:

          distribution: 'corretto'  
          java-version: '17'       
      - name: Install Maven

        run: sudo apt-get update && sudo apt-get install -y maven  
      - name: Run JUnit Tests

        working-directory: Spring-Boot-main 

        run: mvn test  
      - name: Generate JUnit Report (optional)
        uses: dorny/test-reporter-action@v2
        with:
          name: junit-report
          path: 'Spring-Boot-main/test.xml' 
