name: UNIT_TEST
 
on:
  workflow_dispatch:  # Triggered manually (adjust if needed)
 
jobs:
 
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Read access to code repository
      packages: write  # Write access for building artifacts
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code (again, for this job)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'  
          java-version: '17'       
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven  
      - name: Run JUnit Tests
        working-directory: Spring-Boot-main 
        run: mvn test  
      - name: Generate JUnit Report (optional)
        uses: dorny/test-reporter-action@v1
        with:
          name: junit-report
          path: 'Spring-Boot-main/target/surefire-reports/*.xml' 
