name: UNIT_TEST

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Change directory to project
        run: cd Spring-Boot-main
      - name: Build with Maven
        run: mvn -B clean package
        working-directory: Spring-Boot-main/pom.xml
      - name: Run JUnit Tests
        run: mvn test
      - name: Generate JUnit Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: '**/target/surefire-reports/*.xml'
